### ISSUE TITLE
Script is not set to automatically download

### ISSUE THREAD

**Issue by butyraldehyde** [75rx/ani-cli-batch#2]
**Describe the bug**

The script doesn't download automatically, instead it just tells me to copy and paste a command.

**To Reproduce**

Run the script and select the option 2.Execute the Download Command.

**Expected behavior**

Should download what I have set.

**Priority**

Low

**Desktop**

OS: OpenSUSE Leap 15.4
Application and all dependencies installed via zypper

**Additional context**

I know you are saying it is having problems, what kind of issues were you seeing that prevented you from reliably using the auto-script? I'm a beginner at this as well, let's see if I can get some ideas down on paper here.

**Comment by 75rx** [comment]
When the download command is executed from the script by selecting the 2nd option from the menu, like you said, fails with ani-cli saying 
    Checking dependencies...
    No results found!

### Steps to reproduce the issue

1. Uncomment lines 58–65 in the ani-cli-batch.sh script
2. Comment / remove the lines 66–71 (including the 71st line)
3. Run the script
4. Search for an anime
5. Execute the download command from within the script's menu

### Current workaround

The download fails when executed from within the script but for some reason, the same download command works perfectly fine when executed by the user in the user's shell. So the script is set up to print the download command in case of any failure in the download process. The user can just copy this command and execute it him/herself to properly download all the anime in his/her download queue.

**Comment by 75rx** [comment]
I've fixed the downloader. It is now working as intended
