### ISSUE TITLE
Using the ani-cli-batch-update script corrupts the ani-cli-batch script

### ISSUE THREAD

**Issue by 75rx** [75rx/ani-cli-batch#3]
wget incorrectly downloads the ani-cli-batch script probably because I'm using the wrong URL.

**Comment by 75rx** [comment]
git is used as a replacement for wget. git is to be replaced with something more appropriate in the future

**Comment by rondo-clo** [comment]
hello i m using it for a while now and now i am facing some issues like

1. it has started to download videos in fragments 
2. it is also downloading the subtitle file with the video while the anime already has subtitles
can you please fix this ,and tell me how to change directory in which anime is downloaded i tried changing the location but that didn't work. Thank you!

**Comment by 75rx** [comment]
Hello, could you open a new issue for this problem?

**Comment by rondo-clo** [comment]
anime are being downloaded without burnedin subtitles

**Comment by rondo-clo** [comment]
could you please do something about this that it starts downloading them like before
or just attach another website to it like AnimeKai "https://animekai.to/home"
